name: CI

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    uses: andregoepel/workflows/.github/workflows/ci-library.yml@main
    with:
      test-filter: "FullyQualifiedName!~E2ETests"
      pack-projects: |
        src/AndreGoepel.AppFoundation.Core/AndreGoepel.AppFoundation.Core.csproj
        src/AndreGoepel.AppFoundation.ServiceDefaults/AndreGoepel.AppFoundation.ServiceDefaults.csproj
        src/AndreGoepel.AppFoundation.MailService/AndreGoepel.AppFoundation.MailService.csproj
        src/AndreGoepel.AppFoundation/AndreGoepel.AppFoundation.csproj
        src/AndreGoepel.AppFoundation.Hosting/AndreGoepel.AppFoundation.Hosting.csproj
        src/AndreGoepel.AppFoundation.Aspire/AndreGoepel.AppFoundation.Aspire.csproj
    secrets:
      NUGET_USER: ${{ secrets.NUGET_USER }}
    permissions:
      id-token: write # NuGet OIDC trusted publishing
      contents: read
