name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build . \
          --file ./src/AndreGoepel.AppFoundation/Dockerfile \
          --tag nerdventurescontainers.azurecr.io/appfoundation:${{ github.sha }} \
          --tag nerdventurescontainers.azurecr.io/appfoundation:latest

    - name: Log in to Azure
      if: github.event_name == 'push'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Log in to Azure Container Registry
      if: github.event_name == 'push'
      run: az acr login --name nerdventurescontainers

    - name: Push image to ACR
      if: github.event_name == 'push'
      run: |
        docker push nerdventurescontainers.azurecr.io/appfoundation:${{ github.sha }}
        docker push nerdventurescontainers.azurecr.io/appfoundation:latest
